name: Unity Game
on:
  push:
jobs:
  build-unity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: "./Block Game"
      
      - name: Build project
        uses: game-ci/unity-builder@v4
        
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
